apiVersion: v2
name: sulfoxide-gold
description: Helm chart to deploy Nginx as external ingress for AtomiCloud's Infrastructure
type: application
version: 1.9.0
appVersion: "4.8.1"
dependencies:
  - name: ingress-nginx
    repository: https://kubernetes.github.io/ingress-nginx
    version: 4.8.1
