serviceTree:
  cluster: &cluster sulfoxide
  landscape: &landscape "1"

tags: &tags
  atomi.cloud/cluster: *cluster
  atomi.cloud/landscape: *landscape

ingress-nginx:
  commonLabels:
    <<: *tags
  controller:
    annotations:
      <<: *tags
    resources:
      limits:
        cpu: 4
        memory: 8Gi
      requests:
        cpu: 100m
        memory: 256Mi
    replicaCount: 2
    podLabels:
      <<: *tags
