# -- AtomiCloud Service Tree. See [ServiceTree](https://atomicloud.larksuite.com/wiki/OkfJwTXGFiMJkrk6W3RuwRrZs64?theme=DARK&contentTheme=DARK#MHw5d76uDo2tBLx86cduFQMRsBb)
serviceTree:
  platform: &platform sulfoxide
  service: &service gold
  layer: &layer "1"

# -- Kubernetes labels and annotations, following Service Tree
tags: &tags
  atomi.cloud/platform: *platform
  atomi.cloud/service: *service
  atomi.cloud/layer: *layer

# -- YAML Anchor for PodSecurityContext
podSecurityContext: &podSecurityContext
  runAsUser: 1000
  runAsGroup: 1000
  fsGroup: 1000
  runAsNonRoot: true

# -- YAML Anchor for SecurityContext
securityContext: &securityContext
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 3000
  capabilities:
    drop:
      - ALL

# -- External Ingress Controller configuration. See [Nginx Helm Chart](https://docs.nginx.com/nginx-ingress-controller/installation/installation-with-helm/)
ingress-nginx:
  podSecurityPolicy:
    <<: *podSecurityContext
  commonLabels:
    <<: *tags
  controller:
    extraArgs:
      enable-ssl-passthrough: "true"
    annotations:
      <<: *tags
    podSecurityContext:
      <<: *podSecurityContext
    resources:
      limits:
        cpu: 4
        memory: 8Gi
      requests:
        cpu: 100m
        memory: 256Mi
    replicaCount: 2
    podLabels:
      <<: *tags
