serviceTree:
  cluster: &cluster opal
  landscape: &landscape entei

tags: &tags
  atomi.cloud/cluster: *cluster
  atomi.cloud/landscape: *landscape

ingress-nginx:

  commonLabels:
    <<: *tags
  controller:
    config:
      enable-opentelemetry: "true"
    opentelemetry:
      enabled: true
    service:
      annotations:
        external-dns.alpha.kubernetes.io/hostname: cluster.atomi.cloud
        external-dns.alpha.kubernetes.io/ttl: "120"
    annotations:
      <<: *tags
    podAnnotations:
      <<: *tags
    labels:
      <<: *tags
    resources:
      limits:
        cpu: 4
        memory: 8Gi
      requests:
        cpu: 100m
        memory: 256Mi
    replicaCount: 2
    podLabels:
      <<: *tags
